name: InstallDependencies
description: 'Installs Go from go.mod with module and build caching'
inputs:
  use-cache:
    description: 'Whether to cache dependencies'
    default: 'true'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        cache: ${{ inputs.use-cache == 'true' }}
        go-version-file: go.mod
        check-latest: true
        cache-dependency-path: "**/go.sum"
