name: InstallDependencies
description: 'Installs Go from go.mod with module and build caching'
inputs:
  use-cache:
    description: 'Whether to cache dependencies'
    default: 'true'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        cache: ${{ inputs.use-cache == 'true' }}
        go-version-file: go.mod
        check-latest: true
        cache-dependency-path: "**/go.sum"
