name: CI-LINT
on:
  push:
    branches:
      - 'main'
      - 'master'
      - 'release-v*'
  pull_request:
  workflow_dispatch:
jobs:
  ci-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read # golangci/golangci-lint-action
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - uses: ./.github/actions/install-deps
    - uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
      with:
        # Keep in sync with GOLANGCI_LINT_VERSION in the Makefile
        version: v2.12.2
